// src/components/chat/ToolCallCard.tsx
import { AlignLeft, File, Search, Terminal } from 'lucide-react'
import { useEffect, useState, type ReactNode } from 'react'

import { getToolOriginal } from '../../api/messages'
import { useChatStore, type AgentPhase } from '../../state/chatStore'
import styles from './ToolCallCard.module.css'
import {
  EDIT_VISIBLE_LINES,
  editPreview,
  editSuggestion,
  exploreSummary,
  hasDetail,
  needsDecision,
  planView,
  subagentCount,
  subagentStepSummary,
  subagentView,
  toolDetail,
  toolSummary,
  type RetrieveView,
  type ChatToolCall,
  type ToolSummary,
  type DiffLine,
  type EditPreview,
  type PlanView,
  type SubagentStepView
} from './toolCallView'

type ToolCallCardProps = {
  call: ChatToolCall
  phase: AgentPhase
  busy: boolean
  buildDisabled?: boolean
  onDecide: (decision: 'approve' | 'reject') => void
  onBuild?: (path: string) => void
  onViewPlan?: (plan: PlanView) => void
}

export function ToolCallCard({
  call,
  phase,
  busy,
  buildDisabled = false,
  onDecide,
  onBuild,
  onViewPlan
}: ToolCallCardProps) {
  const summary = toolSummary(call)
  const decision = needsDecision(call, phase)
  const preview = editPreview(call)
  const detail = toolDetail(call)
  const expandable = (preview != null || hasDetail(call) || detail?.kind === 'shell') && !decision
  const [open, setOpen] = useState(false)

  if (decision) {
    const suggestion = editSuggestion(call)
    const actions = <ApprovalActions busy={busy} onDecide={onDecide} />
    if (suggestion) {
      return <EditDiff preview={suggestion} actions={actions} />
    }
    if (detail?.kind === 'shell') {
      return (
        <ShellCard
          summary={summary}
          command={detail.command}
          output={detail.output}
          originalId={call.original_id}
          actions={actions}
          defaultOpen
        />
      )
    }
    if (detail?.kind === 'mcp') {
      return (
        <McpCard
          key="mcp-approval"
          summary={summary}
          args={detail.args}
          output={detail.output}
          actions={actions}
          defaultOpen
        />
      )
    }
    if (call.name === 'web_search' || call.name === 'web_fetch') {
      const headline = call.name === 'web_search' ? 'the web' : fetchHost(summary.target)
      const detail =
        summary.target && summary.target !== 'the web' && summary.target !== 'a page'
          ? summary.target
          : null
      return (
        <div className={styles.webApproval}>
          <div className={styles.webApprovalBody}>
            <p className={styles.approvalText}>
              <ToolIcon name={call.name} />
              <span className={styles.verb}>{summary.verb}</span>
              <span className={styles.target}>{headline}</span>
            </p>
            {detail ? <p className={styles.webDetail}>{detail}</p> : null}
          </div>
          {actions}
        </div>
      )
    }
    return (
      <div className={styles.approval}>
        <p className={styles.approvalText}>
          <span className={styles.verb}>{summary.verb}</span>
          <SummaryLabel summary={summary} />
        </p>
        {actions}
      </div>
    )
  }

  const status = statusOf(call, phase)

  if (call.name === 'delegate') {
    return <DelegateCard call={call} status={status} />
  }

  const saved = planView(call)
  if (saved) {
    return (
      <PlanCard
        plan={saved}
        buildDisabled={buildDisabled || saved.path.length === 0}
        onBuild={() => {
          if (saved.path && onBuild) {
            onBuild(saved.path)
          }
        }}
        onView={() => onViewPlan?.(saved)}
      />
    )
  }

  if (preview && status !== 'failed') {
    return <EditDiff preview={preview} />
  }

  if (detail?.kind === 'shell') {
    return (
      <ShellCard
        summary={summary}
        command={detail.command}
        output={detail.output}
        originalId={call.original_id}
        status={<StatusMark status={status} />}
      />
    )
  }

  if (detail?.kind === 'retrieve') {
    return (
      <RetrieveCard summary={summary} view={detail.view} status={<StatusMark status={status} />} />
    )
  }

  if (detail?.kind === 'mcp') {
    return (
      <McpCard
        key="mcp-result"
        summary={summary}
        args={detail.args}
        output={detail.output}
        originalId={call.original_id}
        status={<StatusMark status={status} />}
        defaultOpen={false}
      />
    )
  }

  const header = (
    <button
      type="button"
      className={`${open && detail?.kind === 'code' ? styles.editRow : styles.row} ${status === 'failed' ? styles.rowFailed : ''}`}
      aria-expanded={expandable ? open : undefined}
      aria-invalid={status === 'failed' ? true : undefined}
      disabled={!expandable}
      onClick={() => {
        if (expandable) {
          setOpen((current) => !current)
        }
      }}
    >
      <ToolIcon name={call.name} />
      <span className={styles.verb}>{summary.verb}</span>
      <SummaryLabel summary={summary} />
      <StatusMark status={status} />
    </button>
  )

  if (open && detail?.kind === 'code') {
    return (
      <div className={styles.shell}>
        {header}
        <Detail detail={detail} panel />
      </div>
    )
  }

  return (
    <div className={styles.call}>
      {header}
      {open && detail ? <Detail detail={detail} /> : null}
    </div>
  )
}

function statusOf(call: ChatToolCall, phase: AgentPhase): 'running' | 'failed' | null {
  if (
    call.execution_status === 'failed' ||
    call.execution_status === 'cancelled' ||
    call.execution_status === 'timed_out'
  ) {
    return 'failed'
  }
  if (call.execution_status === 'succeeded') {
    return null
  }
  if (phase !== 'idle' || call.execution_status === 'running') {
    return 'running'
  }
  return null
}

function PlanCard({
  plan,
  buildDisabled,
  onBuild,
  onView
}: {
  plan: PlanView
  buildDisabled: boolean
  onBuild: () => void
  onView: () => void
}) {
  return (
    <div className={styles.planCard}>
      <p className={styles.planStatus}>{plan.created ? 'Created Plan' : 'Updated Plan'}</p>
      <p className={styles.planTitle}>{plan.title}</p>
      {plan.summary ? <p className={styles.planSummary}>{plan.summary}</p> : null}
      <div className={styles.planActions}>
        <button type="button" className={styles.viewPlan} onClick={onView}>
          View Plan
        </button>
        <button
          type="button"
          className={styles.planBuild}
          disabled={buildDisabled}
          onClick={onBuild}
        >
          Build
        </button>
      </div>
    </div>
  )
}

function DelegateCard({
  call,
  status
}: {
  call: ChatToolCall
  status: 'running' | 'failed' | null
}) {
  const view = subagentView(call)
  const summary = toolSummary(call)
  const mode = view?.mode ?? 'explore'
  const label = mode === 'explore' ? 'Explore' : 'General'
  const steps = view?.steps ?? []
  const answer = view?.answer ?? ''
  const [open, setOpen] = useState(false)
  const [answerOpen, setAnswerOpen] = useState(false)
  const title = view?.description || summary.target

  return (
    <div className={styles.call}>
      <button
        type="button"
        className={`${styles.row} ${status === 'failed' ? styles.rowFailed : ''}`}
        aria-expanded={open}
        onClick={() => setOpen((current) => !current)}
      >
        {mode === 'explore' ? (
          <span className={styles.exploreSummary}>{view ? exploreSummary(view) : 'Exploring'}</span>
        ) : (
          <>
            <span className={styles.verb}>{label}</span>
            <StatusMark status={status} />
          </>
        )}
      </button>
      {open ? (
        <div className={styles.delegate}>
          {title ? <p className={styles.delegateTitle}>{title}</p> : null}
          {view && mode !== 'explore' ? <p className={styles.meta}>{subagentCount(view)}</p> : null}
          {steps.length > 0 ? (
            <ul className={styles.steps}>
              {steps.map((step, index) => (
                <StepRow key={`${step.name}-${index}`} step={step} />
              ))}
            </ul>
          ) : null}
          {answer ? (
            <button
              type="button"
              className={styles.answerToggle}
              aria-expanded={answerOpen}
              onClick={() => setAnswerOpen((current) => !current)}
            >
              Answer
            </button>
          ) : null}
          {answerOpen && answer ? <pre className={styles.detail}>{answer}</pre> : null}
        </div>
      ) : null}
    </div>
  )
}

function StepRow({ step }: { step: SubagentStepView }) {
  const summary = subagentStepSummary(step)
  const failed = step.status === 'denied' || step.status === 'failed'
  return (
    <li className={`${styles.step} ${failed ? styles.rowFailed : ''}`}>
      <ToolIcon name={step.name} />
      <span className={styles.verb}>{summary.verb}</span>
      <SummaryLabel summary={summary} />
      {step.status === 'running' ? <span className={styles.spinner} aria-label="Running" /> : null}
    </li>
  )
}

function SummaryLabel({ summary }: { summary: ToolSummary }) {
  if (!summary.target && !summary.range) {
    return null
  }
  return (
    <>
      {summary.target ? <span className={styles.target}>{summary.target}</span> : null}
      {summary.range ? <span className={styles.range}>{summary.range}</span> : null}
    </>
  )
}

function StatusMark({ status }: { status: 'running' | 'failed' | null }) {
  if (status === 'running') {
    return <span className={styles.spinner} aria-label="Running" />
  }
  return null
}

function fetchHost(url: string): string {
  try {
    return new URL(url).host || 'a page'
  } catch {
    return 'a page'
  }
}

function ToolIcon({ name }: { name: string }) {
  const icon = { className: styles.icon, size: 14, strokeWidth: 1.4, 'aria-hidden': true }
  if (name === 'retrieve') {
    return <AlignLeft {...icon} />
  }
  if (name === 'shell') {
    return <Terminal {...icon} />
  }
  if (name === 'grep' || name === 'find' || name === 'web_search') {
    return <Search {...icon} />
  }
  return <File {...icon} />
}

function ApprovalActions({
  busy,
  onDecide
}: {
  busy: boolean
  onDecide: (decision: 'approve' | 'reject') => void
}) {
  return (
    <div className={styles.actions}>
      <button
        type="button"
        className={styles.reject}
        disabled={busy}
        onClick={() => onDecide('reject')}
      >
        Reject
      </button>
      <button
        type="button"
        className={styles.approve}
        disabled={busy}
        onClick={() => onDecide('approve')}
      >
        Approve
      </button>
    </div>
  )
}

function EditDiff({ preview, actions }: { preview: EditPreview; actions?: ReactNode }) {
  const [open, setOpen] = useState(false)
  const canExpand = preview.lines.length > EDIT_VISIBLE_LINES || preview.hidden > 0
  const firstChange = preview.lines.findIndex((line) => line.kind !== 'context')
  const from = firstChange < 0 ? 0 : firstChange
  const visible = open ? preview.lines : preview.lines.slice(from, from + EDIT_VISIBLE_LINES)
  return (
    <div className={styles.edit}>
      <div className={styles.editHead}>
        <button
          type="button"
          className={styles.editRow}
          aria-expanded={canExpand ? open : undefined}
          disabled={!canExpand}
          onClick={() => {
            if (canExpand) {
              setOpen((current) => !current)
            }
          }}
        >
          <span className={styles.editPath} title={preview.path}>
            {preview.path}
          </span>
          <span className={styles.editCounts}>
            <span className={styles.add}>+{preview.additions}</span>
            <span className={styles.del}>-{preview.deletions}</span>
          </span>
        </button>
        {actions}
      </div>
      <DiffView lines={visible} hidden={open ? preview.hidden : 0} />
    </div>
  )
}

function DiffView({ lines, hidden }: { lines: DiffLine[]; hidden: number }) {
  return (
    <div className={styles.diff}>
      {lines.map((line, index) => (
        <div key={index} className={styles.diffLine} data-kind={line.kind}>
          <span className={styles.lineNo}>{line.lineNo}</span>
          <span className={styles.mark}>
            {line.kind === 'add' ? '+' : line.kind === 'del' ? '−' : ' '}
          </span>
          <span className={styles.diffText}>{line.text}</span>
        </div>
      ))}
      {hidden > 0 ? <p className={styles.more}>{hidden} more lines</p> : null}
    </div>
  )
}

function ShellCard({
  summary,
  command,
  output,
  originalId,
  actions,
  status,
  defaultOpen = false
}: {
  summary: { verb: string; target: string }
  command: string
  output: string
  originalId?: string | null
  actions?: ReactNode
  status?: ReactNode
  defaultOpen?: boolean
}) {
  const sessionId = useChatStore((state) => state.activeSessionId)
  const shown = useCappedOutput(sessionId, originalId, output)
  const [open, setOpen] = useState(defaultOpen)
  const [openedForApproval, setOpenedForApproval] = useState(defaultOpen)
  if (defaultOpen && !openedForApproval) {
    setOpenedForApproval(true)
    setOpen(true)
  }
  const header = (
    <div className={styles.editHead}>
      <button
        type="button"
        className={open ? styles.editRow : styles.row}
        aria-expanded={open}
        onClick={() => setOpen((current) => !current)}
      >
        <ToolIcon name="shell" />
        <span className={styles.verb}>{summary.verb}</span>
        <SummaryLabel summary={summary} />
        {status}
      </button>
      {actions}
    </div>
  )
  if (!open) {
    return header
  }
  return (
    <div className={styles.shell}>
      {header}
      <ShellBody command={command} output={shown} compact={!actions} />
    </div>
  )
}

function useCappedOutput(
  sessionId: string | null,
  originalId: string | null | undefined,
  fallback: string
): string {
  const [loaded, setLoaded] = useState<{ id: string; text: string } | null>(null)
  useEffect(() => {
    if (!sessionId || !originalId) {
      return
    }
    let cancelled = false
    const id = originalId
    getToolOriginal(sessionId, id)
      .then((body) => {
        if (cancelled) {
          return
        }
        const text =
          body.kind === 'mcp'
            ? body.text
            : [body.stdout, body.stderr].filter((part) => part.length > 0).join('\n')
        if (text.length > 0) {
          setLoaded({ id, text })
        }
      })
      .catch(() => {
        // A missing row shows the transcript text.
      })
    return () => {
      cancelled = true
    }
  }, [sessionId, originalId])
  if (loaded && originalId && loaded.id === originalId) {
    return loaded.text
  }
  return fallback
}

function McpCard({
  summary,
  args,
  output,
  originalId,
  actions,
  status,
  defaultOpen = false
}: {
  summary: { verb: string; target: string }
  args: string
  output: string
  originalId?: string | null
  actions?: ReactNode
  status?: ReactNode
  defaultOpen?: boolean
}) {
  const sessionId = useChatStore((state) => state.activeSessionId)
  const shown = useCappedOutput(sessionId, originalId, output)
  const [open, setOpen] = useState(defaultOpen)
  const [openedForApproval, setOpenedForApproval] = useState(defaultOpen)
  if (defaultOpen && !openedForApproval) {
    setOpenedForApproval(true)
    setOpen(true)
  }
  const header = (
    <div className={styles.editHead}>
      <button
        type="button"
        className={open ? styles.editRow : styles.row}
        aria-expanded={open}
        onClick={() => setOpen((current) => !current)}
      >
        <span className={styles.verb}>{summary.verb}</span>
        <SummaryLabel summary={summary} />
        {status}
      </button>
      {actions}
    </div>
  )
  if (!open) {
    return header
  }
  return (
    <div className={styles.shell}>
      {header}
      <pre className={styles.shellBody}>
        {args}
        {shown ? `\n${shown}` : ''}
      </pre>
    </div>
  )
}

function RetrieveCard({
  summary,
  view,
  status
}: {
  summary: ToolSummary
  view: RetrieveView
  status?: ReactNode
}) {
  const [open, setOpen] = useState(false)
  const page =
    view.totalLines > 0
      ? `lines ${view.startLine}–${view.endLine || view.startLine} of ${view.totalLines}`
      : null
  const facts = [
    view.stream === 'both' ? 'stdout and stderr' : view.stream,
    view.exitCode != null ? `exit ${view.exitCode}` : null,
    view.truncated ? 'truncated' : null,
    view.raw ? 'raw' : null,
    page,
    view.nextOffset != null ? `more from L${view.nextOffset}` : null
  ].filter((fact): fact is string => fact != null && fact.length > 0)
  const header = (
    <button
      type="button"
      className={open ? styles.editRow : styles.row}
      aria-expanded={open}
      onClick={() => setOpen((current) => !current)}
    >
      <ToolIcon name="retrieve" />
      <span className={styles.verb}>{summary.verb}</span>
      <SummaryLabel summary={summary} />
      {status}
    </button>
  )
  if (!open) {
    return header
  }
  return (
    <div className={styles.shell}>
      {header}
      <div className={styles.retrieve}>
        <p className={styles.retrieveMeta}>{facts.join(' · ')}</p>
        {view.stdout ? <LogLines text={view.stdout} startLine={view.startLine} /> : null}
        {view.stderr ? (
          <>
            <p className={styles.retrieveStream}>stderr</p>
            <LogLines
              text={view.stderr}
              startLine={view.stream === 'stderr' ? view.startLine : 1}
            />
          </>
        ) : null}
        {!view.stdout && !view.stderr ? <p className={styles.retrieveMeta}>Empty page</p> : null}
      </div>
    </div>
  )
}

function LogLines({ text, startLine }: { text: string; startLine: number }) {
  const lines = text.split('\n')
  return (
    <div className={styles.retrieveLog}>
      {lines.map((line, index) => (
        <span
          key={index}
          className={line.startsWith('<<<ROBI_') ? styles.markerLine : styles.codeLine}
        >
          <span className={styles.lineNo}>{startLine + index}</span>
          <span>{line}</span>
        </span>
      ))}
    </div>
  )
}

function ShellBody({
  command,
  output,
  compact = false
}: {
  command: string
  output: string
  compact?: boolean
}) {
  return (
    <pre className={compact ? `${styles.shellBody} ${styles.shellBodyCompact}` : styles.shellBody}>
      <span className={styles.shellCommand}>
        <span className={styles.prompt}>$</span> {command}
      </span>
      {output}
    </pre>
  )
}

function Detail({
  detail,
  panel = false
}: {
  detail: Exclude<
    NonNullable<ReturnType<typeof toolDetail>>,
    { kind: 'shell' } | { kind: 'mcp' } | { kind: 'retrieve' }
  >
  panel?: boolean
}) {
  if (detail.kind === 'error') {
    return <pre className={styles.error}>{detail.text}</pre>
  }
  if (detail.kind === 'code') {
    return (
      <pre className={panel ? styles.shellBody : styles.detail}>
        {detail.lines.map((line, index) => (
          <span key={index} className={styles.codeLine}>
            <span className={styles.lineNo}>{detail.startLine + index}</span>
            <span>{line}</span>
          </span>
        ))}
      </pre>
    )
  }
  return (
    <pre className={styles.detail}>
      {detail.lines.map((line, index) => (
        <span key={index} className={styles.plainLine}>
          {line}
        </span>
      ))}
    </pre>
  )
}

// src/features/chat/ToolCallCard.tsx
/** @jsxImportSource solid-js */
import { BarsBottomLeft, CommandLine, Document, MagnifyingGlass } from '../../components/ui/icons'
import { createEffect, createSignal, For, onCleanup, Show, type JSX } from 'solid-js'

import { getToolOriginal } from '../../api/messages'
import { type AgentPhase } from '../../state/chatStore'
import { chat } from '../../state/chatStore'
import styles from './ToolCallCard.module.css'
import {
  EDIT_VISIBLE_LINES,
  editPreview,
  editSuggestion,
  exploreSummary,
  hasDetail,
  needsDecision,
  planView,
  subagentCount,
  subagentStepSummary,
  subagentView,
  toolDetail,
  toolSummary,
  type RetrieveView,
  type ChatToolCall,
  type ToolSummary,
  type DiffLine,
  type EditPreview,
  type PlanView,
  type SubagentStepView
} from './toolCallView'
export function ToolCallCard(props: {
  call: ChatToolCall
  phase: AgentPhase
  busy: boolean
  buildDisabled?: boolean
  onDecide: (decision: 'approve' | 'reject') => void
  onBuild?: (path: string) => void
  onViewPlan?: (plan: PlanView) => void
}) {
  const summary = () => toolSummary(props.call)
  const decision = () => needsDecision(props.call, props.phase)
  const preview = () => editPreview(props.call)
  const detail = () => toolDetail(props.call)
  const expandable = () =>
    (preview() != null || hasDetail(props.call) || detail()?.kind === 'shell') && !decision()
  const [open, setOpen] = createSignal(false)
  const status = () => statusOf(props.call, props.phase)
  const shellDetail = () => {
    const next = detail()
    return next?.kind === 'shell' ? next : null
  }
  const mcpDetail = () => {
    const next = detail()
    return next?.kind === 'mcp' ? next : null
  }

  return (
    <Show
      when={!decision()}
      fallback={
        <ApprovalBody
          call={props.call}
          summary={summary()}
          detail={detail()}
          busy={props.busy}
          onDecide={props.onDecide}
        />
      }
    >
      <Show when={props.call.name === 'delegate'} fallback={null}>
        <DelegateCard call={props.call} status={status()} />
      </Show>
      <Show when={props.call.name !== 'delegate' && planView(props.call)}>
        {(saved) => (
          <PlanCard
            plan={saved()}
            buildDisabled={(props.buildDisabled ?? false) || saved().path.length === 0}
            onBuild={() => {
              if (saved().path && props.onBuild) {
                props.onBuild(saved().path)
              }
            }}
            onView={() => props.onViewPlan?.(saved())}
          />
        )}
      </Show>
      <Show
        when={
          props.call.name !== 'delegate' &&
          !planView(props.call) &&
          preview() &&
          status() !== 'failed'
        }
      >
        <EditDiff preview={preview()!} />
      </Show>
      <Show
        when={
          props.call.name !== 'delegate' &&
          !planView(props.call) &&
          !(preview() && status() !== 'failed') &&
          detail()?.kind === 'shell'
            ? detail()
            : null
        }
      >
        <ShellCard
          summary={summary()}
          command={shellDetail()?.command ?? ''}
          output={shellDetail()?.output ?? ''}
          originalId={props.call.original_id}
          status={<StatusMark status={status()} />}
        />
      </Show>
      <Show
        when={
          detail()?.kind === 'retrieve' && props.call.name !== 'delegate' && !planView(props.call)
        }
      >
        <RetrieveCard
          summary={summary()}
          view={(detail() as { kind: 'retrieve'; view: RetrieveView }).view}
          status={<StatusMark status={status()} />}
        />
      </Show>
      <Show
        when={
          detail()?.kind === 'mcp' && !decision() && props.call.name !== 'delegate'
            ? detail()
            : null
        }
      >
        <McpCard
          summary={summary()}
          args={mcpDetail()?.args ?? ''}
          output={mcpDetail()?.output ?? ''}
          originalId={props.call.original_id}
          status={<StatusMark status={status()} />}
        />
      </Show>
      <Show
        when={
          props.call.name !== 'delegate' &&
          !planView(props.call) &&
          !(preview() && status() !== 'failed') &&
          detail()?.kind !== 'shell' &&
          detail()?.kind !== 'retrieve' &&
          detail()?.kind !== 'mcp'
        }
      >
        <div class={open() && detail() ? styles.shell : styles.call}>
          <button
            type="button"
            class={`${open() && detail() ? styles.editRow : styles.row} ${status() === 'failed' ? styles.rowFailed : ''}`}
            aria-expanded={expandable() ? open() : undefined}
            aria-invalid={status() === 'failed' ? true : undefined}
            disabled={!expandable()}
            onClick={() => {
              if (expandable()) {
                setOpen((current) => !current)
              }
            }}
          >
            <ToolIcon name={props.call.name} />
            <span class={styles.verb}>{summary().verb}</span>
            <SummaryLabel summary={summary()} />
            <StatusMark status={status()} />
          </button>
          <Show when={open() && detail()}>
            <Detail detail={detail()!} panel />
          </Show>
        </div>
      </Show>
    </Show>
  )
}

function ApprovalBody(props: {
  call: ChatToolCall
  summary: ToolSummary
  detail: ReturnType<typeof toolDetail>
  busy: boolean
  onDecide: (decision: 'approve' | 'reject') => void
}) {
  const suggestion = () => editSuggestion(props.call)
  const actions = <ApprovalActions busy={props.busy} onDecide={props.onDecide} />
  return (
    <Show when={!suggestion()} fallback={<EditDiff preview={suggestion()!} actions={actions} />}>
      <Show
        when={props.detail?.kind !== 'shell'}
        fallback={
          <ShellCard
            summary={props.summary}
            command={props.detail?.kind === 'shell' ? props.detail.command : ''}
            output={props.detail?.kind === 'shell' ? props.detail.output : ''}
            originalId={props.call.original_id}
            actions={actions}
            defaultOpen
          />
        }
      >
        <Show
          when={props.detail?.kind !== 'mcp'}
          fallback={
            <McpCard
              summary={props.summary}
              args={props.detail?.kind === 'mcp' ? props.detail.args : ''}
              output={props.detail?.kind === 'mcp' ? props.detail.output : ''}
              actions={actions}
              defaultOpen
            />
          }
        >
          <Show
            when={props.call.name === 'web_search' || props.call.name === 'web_fetch'}
            fallback={
              <div class={styles.approval}>
                <p class={styles.approvalText}>
                  <span class={styles.verb}>{props.summary.verb}</span>
                  <SummaryLabel summary={props.summary} />
                </p>
                {actions}
              </div>
            }
          >
            <div class={styles.webApproval}>
              <div class={styles.webApprovalBody}>
                <p class={styles.approvalText}>
                  <ToolIcon name={props.call.name} />
                  <span class={styles.verb}>{props.summary.verb}</span>
                  <span class={styles.target}>
                    {props.call.name === 'web_search' ? 'the web' : fetchHost(props.summary.target)}
                  </span>
                </p>
              </div>
              {actions}
            </div>
          </Show>
        </Show>
      </Show>
    </Show>
  )
}

function statusOf(call: ChatToolCall, phase: AgentPhase): 'running' | 'failed' | null {
  if (
    call.execution_status === 'failed' ||
    call.execution_status === 'cancelled' ||
    call.execution_status === 'timed_out'
  ) {
    return 'failed'
  }
  if (call.execution_status === 'succeeded') {
    return null
  }
  if (phase !== 'idle' || call.execution_status === 'running') {
    return 'running'
  }
  return null
}

function PlanCard(props: {
  plan: PlanView
  buildDisabled: boolean
  onBuild: () => void
  onView: () => void
}) {
  return (
    <div class={styles.planCard}>
      <p class={styles.planStatus}>{props.plan.created ? 'Created Plan' : 'Updated Plan'}</p>
      <p class={styles.planTitle}>{props.plan.title}</p>
      <Show when={props.plan.summary}>
        <p class={styles.planSummary}>{props.plan.summary}</p>
      </Show>
      <div class={styles.planActions}>
        <button type="button" class={styles.viewPlan} onClick={() => props.onView()}>
          View Plan
        </button>
        <button
          type="button"
          class={styles.planBuild}
          disabled={props.buildDisabled}
          onClick={() => props.onBuild()}
        >
          Build
        </button>
      </div>
    </div>
  )
}

function DelegateCard(props: { call: ChatToolCall; status: 'running' | 'failed' | null }) {
  const view = () => subagentView(props.call)
  const summary = () => toolSummary(props.call)
  const mode = () => view()?.mode ?? 'explore'
  const [open, setOpen] = createSignal(false)
  const [answerOpen, setAnswerOpen] = createSignal(false)
  return (
    <div class={styles.call}>
      <button
        type="button"
        class={`${styles.row} ${props.status === 'failed' ? styles.rowFailed : ''}`}
        aria-expanded={open()}
        onClick={() => setOpen((current) => !current)}
      >
        <Show
          when={mode() === 'explore'}
          fallback={
            <>
              <span class={styles.verb}>General</span>
              <StatusMark status={props.status} />
            </>
          }
        >
          <span class={styles.exploreSummary}>
            {view() ? exploreSummary(view()!) : 'Exploring'}
          </span>
        </Show>
      </button>
      <Show when={open()}>
        <div class={styles.delegate}>
          <Show when={view()?.description || summary().target}>
            <p class={styles.delegateTitle}>{view()?.description || summary().target}</p>
          </Show>
          <Show when={view() && mode() !== 'explore'}>
            <p class={styles.meta}>{subagentCount(view()!)}</p>
          </Show>
          <Show when={(view()?.steps ?? []).length > 0}>
            <ul class={styles.steps}>
              <For each={view()?.steps ?? []}>{(step) => <StepRow step={step} />}</For>
            </ul>
          </Show>
          <Show when={view()?.answer}>
            <button
              type="button"
              class={styles.answerToggle}
              aria-expanded={answerOpen()}
              onClick={() => setAnswerOpen((current) => !current)}
            >
              Answer
            </button>
          </Show>
          <Show when={answerOpen() && view()?.answer}>
            <pre class={styles.detail}>{view()?.answer}</pre>
          </Show>
        </div>
      </Show>
    </div>
  )
}

function StepRow(props: { step: SubagentStepView }) {
  const summary = () => subagentStepSummary(props.step)
  const failed = () => props.step.status === 'denied' || props.step.status === 'failed'
  return (
    <li class={`${styles.step} ${failed() ? styles.rowFailed : ''}`}>
      <ToolIcon name={props.step.name} />
      <span class={styles.verb}>{summary().verb}</span>
      <SummaryLabel summary={summary()} />
      <Show when={props.step.status === 'running'}>
        <span class={styles.spinner} aria-label="Running" />
      </Show>
    </li>
  )
}

function SummaryLabel(props: { summary: ToolSummary }) {
  return (
    <Show when={props.summary.target || props.summary.range}>
      <Show when={props.summary.target}>
        <span class={styles.target}>{props.summary.target}</span>
      </Show>
      <Show when={props.summary.range}>
        <span class={styles.range}>{props.summary.range}</span>
      </Show>
    </Show>
  )
}

function StatusMark(props: { status: 'running' | 'failed' | null }) {
  return (
    <Show when={props.status === 'running'}>
      <span class={styles.spinner} aria-label="Running" />
    </Show>
  )
}

function fetchHost(url: string): string {
  try {
    return new URL(url).host || 'a page'
  } catch {
    return 'a page'
  }
}

function ToolIcon(props: { name: string }) {
  const icon = { class: styles.icon, size: 14, 'aria-hidden': true as const }
  if (props.name === 'retrieve') {
    return <BarsBottomLeft {...icon} />
  }
  if (props.name === 'shell') {
    return <CommandLine {...icon} />
  }
  if (props.name === 'grep' || props.name === 'find' || props.name === 'web_search') {
    return <MagnifyingGlass {...icon} />
  }
  return <Document {...icon} />
}

function ApprovalActions(props: {
  busy: boolean
  onDecide: (decision: 'approve' | 'reject') => void
}) {
  return (
    <div class={styles.actions}>
      <button
        type="button"
        class={styles.reject}
        disabled={props.busy}
        onClick={() => props.onDecide('reject')}
      >
        Reject
      </button>
      <button
        type="button"
        class={styles.approve}
        disabled={props.busy}
        onClick={() => props.onDecide('approve')}
      >
        Approve
      </button>
    </div>
  )
}

function EditDiff(props: { preview: EditPreview; actions?: JSX.Element }) {
  const [open, setOpen] = createSignal(false)
  const canExpand = () =>
    props.preview.lines.length > EDIT_VISIBLE_LINES || props.preview.hidden > 0
  const visible = () => {
    if (open()) {
      return props.preview.lines
    }
    const firstChange = props.preview.lines.findIndex((line) => line.kind !== 'context')
    const from = firstChange < 0 ? 0 : firstChange
    return props.preview.lines.slice(from, from + EDIT_VISIBLE_LINES)
  }
  return (
    <div class={styles.edit}>
      <div class={styles.editHead}>
        <button
          type="button"
          class={styles.editRow}
          aria-expanded={canExpand() ? open() : undefined}
          disabled={!canExpand()}
          onClick={() => {
            if (canExpand()) {
              setOpen((current) => !current)
            }
          }}
        >
          <span class={styles.editPath} title={props.preview.path}>
            {props.preview.path}
          </span>
          <span class={styles.editCounts}>
            <span class={styles.add}>+{props.preview.additions}</span>
            <span class={styles.del}>-{props.preview.deletions}</span>
          </span>
        </button>
        {props.actions}
      </div>
      <DiffView lines={visible()} hidden={open() ? props.preview.hidden : 0} />
    </div>
  )
}

function DiffView(props: { lines: DiffLine[]; hidden: number }) {
  return (
    <div class={styles.diff}>
      <For each={props.lines}>
        {(line) => (
          <div class={styles.diffLine} data-kind={line.kind}>
            <span class={styles.lineNo}>{line.lineNo}</span>
            <span class={styles.mark}>
              {line.kind === 'add' ? '+' : line.kind === 'del' ? '−' : ' '}
            </span>
            <span class={styles.diffText}>{line.text}</span>
          </div>
        )}
      </For>
      <Show when={props.hidden > 0}>
        <p class={styles.more}>{props.hidden} more lines</p>
      </Show>
    </div>
  )
}

function useCappedOutput(
  sessionId: () => string | null,
  originalId: () => string | null | undefined,
  fallback: () => string
): () => string {
  const [loaded, setLoaded] = createSignal<{ id: string; text: string } | null>(null)
  createEffect(() => {
    const session = sessionId()
    const id = originalId()
    if (!session || !id) {
      return
    }
    let cancelled = false
    void getToolOriginal(session, id)
      .then((body) => {
        if (cancelled) {
          return
        }
        const text =
          body.kind === 'mcp'
            ? body.text
            : [body.stdout, body.stderr].filter((part) => part.length > 0).join('\n')
        if (text.length > 0) {
          setLoaded({ id, text })
        }
      })
      .catch(() => {})
    onCleanup(() => {
      cancelled = true
    })
  })
  return () => {
    const current = loaded()
    const id = originalId()
    if (current && id && current.id === id) {
      return current.text
    }
    return fallback()
  }
}

function ShellCard(props: {
  summary: { verb: string; target: string }
  command: string
  output: string
  originalId?: string | null
  actions?: JSX.Element
  status?: JSX.Element
  defaultOpen?: boolean
}) {
  const shown = useCappedOutput(
    () => chat.activeSessionId,
    () => props.originalId,
    () => props.output
  )
  const [open, setOpen] = createSignal(props.defaultOpen ?? false)
  return (
    <Show
      when={open()}
      fallback={
        <div class={styles.editHead}>
          <button
            type="button"
            class={styles.row}
            aria-expanded={false}
            onClick={() => setOpen(true)}
          >
            <ToolIcon name="shell" />
            <span class={styles.verb}>{props.summary.verb}</span>
            <SummaryLabel summary={props.summary} />
            {props.status}
          </button>
          {props.actions}
        </div>
      }
    >
      <div class={styles.shell}>
        <div class={styles.editHead}>
          <button
            type="button"
            class={styles.editRow}
            aria-expanded={true}
            onClick={() => setOpen(false)}
          >
            <ToolIcon name="shell" />
            <span class={styles.verb}>{props.summary.verb}</span>
            <SummaryLabel summary={props.summary} />
            {props.status}
          </button>
          {props.actions}
        </div>
        <ShellBody command={props.command} output={shown()} compact={!props.actions} />
      </div>
    </Show>
  )
}

function McpCard(props: {
  summary: { verb: string; target: string }
  args: string
  output: string
  originalId?: string | null
  actions?: JSX.Element
  status?: JSX.Element
  defaultOpen?: boolean
}) {
  const shown = useCappedOutput(
    () => chat.activeSessionId,
    () => props.originalId,
    () => props.output
  )
  const [open, setOpen] = createSignal(props.defaultOpen ?? false)
  return (
    <div class={open() ? styles.shell : styles.call}>
      <div class={styles.editHead}>
        <button
          type="button"
          class={open() ? styles.editRow : styles.row}
          aria-expanded={open()}
          onClick={() => setOpen((current) => !current)}
        >
          <span class={styles.verb}>{props.summary.verb}</span>
          <SummaryLabel summary={props.summary} />
          {props.status}
        </button>
        {props.actions}
      </div>
      <Show when={open()}>
        <pre class={styles.shellBody}>
          {props.args}
          {shown() ? `\n${shown()}` : ''}
        </pre>
      </Show>
    </div>
  )
}

function RetrieveCard(props: { summary: ToolSummary; view: RetrieveView; status?: JSX.Element }) {
  const [open, setOpen] = createSignal(false)
  const facts = () => {
    const view = props.view
    const page =
      view.totalLines > 0
        ? `lines ${view.startLine}–${view.endLine || view.startLine} of ${view.totalLines}`
        : null
    return [
      view.stream === 'both' ? 'stdout and stderr' : view.stream,
      view.exitCode != null ? `exit ${view.exitCode}` : null,
      view.truncated ? 'truncated' : null,
      view.raw ? 'raw' : null,
      page,
      view.nextOffset != null ? `more from L${view.nextOffset}` : null
    ].filter((fact): fact is string => fact != null && fact.length > 0)
  }
  return (
    <div class={open() ? styles.shell : styles.call}>
      <button
        type="button"
        class={open() ? styles.editRow : styles.row}
        aria-expanded={open()}
        onClick={() => setOpen((current) => !current)}
      >
        <ToolIcon name="retrieve" />
        <span class={styles.verb}>{props.summary.verb}</span>
        <SummaryLabel summary={props.summary} />
        {props.status}
      </button>
      <Show when={open()}>
        <div class={styles.retrieve}>
          <p class={styles.retrieveMeta}>{facts().join(' · ')}</p>
          <Show when={props.view.stdout}>
            <LogLines text={props.view.stdout} startLine={props.view.startLine} />
          </Show>
          <Show when={props.view.stderr}>
            <p class={styles.retrieveStream}>stderr</p>
            <LogLines
              text={props.view.stderr}
              startLine={props.view.stream === 'stderr' ? props.view.startLine : 1}
            />
          </Show>
          <Show when={!props.view.stdout && !props.view.stderr}>
            <p class={styles.retrieveMeta}>Empty page</p>
          </Show>
        </div>
      </Show>
    </div>
  )
}

function LogLines(props: { text: string; startLine: number }) {
  const lines = () => props.text.split('\n')
  return (
    <div class={styles.retrieveLog}>
      <For each={lines()}>
        {(line, index) => (
          <span class={line.startsWith('<<<ROBI_') ? styles.markerLine : styles.codeLine}>
            <span class={styles.lineNo}>{props.startLine + index()}</span>
            <span>{line}</span>
          </span>
        )}
      </For>
    </div>
  )
}

function ShellBody(props: { command: string; output: string; compact?: boolean }) {
  return (
    <pre
      class={props.compact ? `${styles.shellBody} ${styles.shellBodyCompact}` : styles.shellBody}
    >
      <span class={styles.shellCommand}>
        <span class={styles.prompt}>$</span> {props.command}
      </span>
      {props.output}
    </pre>
  )
}

function Detail(props: { detail: NonNullable<ReturnType<typeof toolDetail>>; panel?: boolean }) {
  const body = () => (props.panel ? styles.shellBody : styles.detail)
  return (
    <Show
      when={props.detail.kind !== 'error'}
      fallback={
        <pre class={props.panel ? `${styles.shellBody} ${styles.errorText}` : styles.error}>
          {props.detail.kind === 'error' ? props.detail.text : ''}
        </pre>
      }
    >
      <Show
        when={props.detail.kind === 'code'}
        fallback={
          <pre class={body()}>
            <For each={props.detail.kind === 'lines' ? props.detail.lines : []}>
              {(line) => <span class={styles.plainLine}>{line}</span>}
            </For>
          </pre>
        }
      >
        <pre class={body()}>
          <For each={props.detail.kind === 'code' ? props.detail.lines : []}>
            {(line, index) => (
              <span class={styles.codeLine}>
                <span class={styles.lineNo}>
                  {(props.detail.kind === 'code' ? props.detail.startLine : 1) + index()}
                </span>
                <span>{line}</span>
              </span>
            )}
          </For>
        </pre>
      </Show>
    </Show>
  )
}
