// src/solid/components/review/FileTree.tsx
/** @jsxImportSource solid-js */
import { For, Show } from 'solid-js'

import type { TreeNode } from '../../../components/review/tree'
import styles from '../../../components/review/FileTree.module.css'

export function FileTree(props: {
  nodes: TreeNode[]
  selected: string | null
  onSelect: (path: string) => void
}) {
  return (
    <nav class={styles.tree} aria-label="Changed files">
      <TreeLevel
        nodes={props.nodes}
        depth={0}
        selected={props.selected}
        onSelect={props.onSelect}
      />
    </nav>
  )
}

function TreeLevel(props: {
  nodes: TreeNode[]
  depth: number
  selected: string | null
  onSelect: (path: string) => void
}) {
  return (
    <ul class={styles.list}>
      <For each={props.nodes}>
        {(node) => (
          <li>
            <Show
              when={node.kind === 'dir'}
              fallback={
                <button
                  type="button"
                  class={node.path === props.selected ? styles.fileActive : styles.file}
                  style={{ 'padding-left': `${12 + props.depth * 14}px` }}
                  aria-current={node.path === props.selected ? 'true' : undefined}
                  onClick={() => props.onSelect(node.path)}
                >
                  {node.name}
                </button>
              }
            >
              <div class={styles.dir} style={{ 'padding-left': `${12 + props.depth * 14}px` }}>
                {node.name}
              </div>
              <TreeLevel
                nodes={node.kind === 'dir' ? node.children : []}
                depth={props.depth + 1}
                selected={props.selected}
                onSelect={props.onSelect}
              />
            </Show>
          </li>
        )}
      </For>
    </ul>
  )
}

// src/components/review/FileTree.tsx
import type { TreeNode } from './tree'
import styles from './FileTree.module.css'

type FileTreeProps = {
  nodes: TreeNode[]
  selected: string | null
  onSelect: (path: string) => void
}

export function FileTree({ nodes, selected, onSelect }: FileTreeProps) {
  return (
    <nav className={styles.tree} aria-label="Changed files">
      <TreeLevel nodes={nodes} depth={0} selected={selected} onSelect={onSelect} />
    </nav>
  )
}

function TreeLevel({ nodes, depth, selected, onSelect }: FileTreeProps & { depth: number }) {
  return (
    <ul className={styles.list}>
      {nodes.map((node) => (
        <li key={`${node.kind}:${node.path}`}>
          {node.kind === 'dir' ? (
            <>
              <div className={styles.dir} style={{ paddingLeft: 12 + depth * 14 }}>
                {node.name}
              </div>
              <TreeLevel
                nodes={node.children}
                depth={depth + 1}
                selected={selected}
                onSelect={onSelect}
              />
            </>
          ) : (
            <button
              type="button"
              className={node.path === selected ? styles.fileActive : styles.file}
              style={{ paddingLeft: 12 + depth * 14 }}
              aria-current={node.path === selected ? 'true' : undefined}
              onClick={() => onSelect(node.path)}
            >
              {node.name}
            </button>
          )}
        </li>
      ))}
    </ul>
  )
}
