// src/solid/components/chat/ChatPanel.tsx
/** @jsxImportSource solid-js */
import { createEffect, onCleanup, Show } from 'solid-js'

import type { ChatMessage } from '../../../api/messages'
import type { CatalogModel } from '../../../api/models'
import type { AgentMode } from '../../../api/sessions'
import type { AgentPhase } from '../../../state/chatStore'
import type { AttachmentMeta, FileAttachment } from '../../../components/chat/textAttachments'
import type { PlanView } from '../../../components/chat/toolCallView'
import styles from '../../../components/chat/ChatPanel.module.css'
import { Composer } from './Composer'
import { EditReviewStrip } from './EditReviewStrip'
import { Transcript } from './Transcript'

export type ChatPanelProps = {
  messages: ChatMessage[]
  sessionId: string | null
  echo: string | null
  echoFiles: AttachmentMeta[]
  phase: AgentPhase
  mode: AgentMode
  deciding: boolean
  buildDisabled: boolean
  onDecide: (callId: string, decision: 'approve' | 'reject') => void
  onBuild: (path: string) => void
  onViewPlan: (plan: PlanView) => void
  disabled: boolean
  pending: boolean
  running: boolean
  stopping: boolean
  onStop: () => void
  onSubmit: (text: string, images?: File[], files?: FileAttachment[]) => Promise<boolean>
  models: CatalogModel[]
  modelId: string | null
  effort: string | null
  defaultModelId: string
  defaultEffort: string | null
  onModeChange: (mode: AgentMode) => void
  onModelChange: (model: string | null) => void
  onEffortChange: (effort: string | null) => void
  draftKey: string
  pendingText?: string | null
  workspaceId?: string | null
  onCompact?: () => void
  compacting?: boolean
  showReviewStrip?: boolean
}

export function ChatPanel(props: ChatPanelProps) {
  let thread: HTMLDivElement | undefined
  let dock: HTMLDivElement | undefined

  createEffect(() => {
    props.sessionId
    props.draftKey
    props.showReviewStrip
    const dockNode = dock
    const threadNode = thread
    if (!dockNode || !threadNode) {
      return
    }
    const apply = () => {
      threadNode.style.setProperty('--dock-height', `${dockNode.offsetHeight}px`)
      const composer = dockNode.lastElementChild
      if (composer instanceof HTMLElement) {
        threadNode.style.setProperty('--composer-height', `${composer.offsetHeight}px`)
      }
    }
    apply()
    const observer = new ResizeObserver(apply)
    observer.observe(dockNode)
    onCleanup(() => observer.disconnect())
  })

  return (
    <div class={styles.chat}>
      <div class={styles.thread} ref={thread}>
        <Transcript
          messages={props.messages}
          sessionId={props.sessionId}
          echo={props.echo}
          echoFiles={props.echoFiles}
          phase={props.phase}
          mode={props.mode}
          deciding={props.deciding}
          buildDisabled={props.buildDisabled}
          onDecide={props.onDecide}
          onBuild={props.onBuild}
          onViewPlan={props.onViewPlan}
        />
        <div class={styles.dock} ref={dock}>
          <Show when={props.showReviewStrip && props.sessionId}>
            <EditReviewStrip sessionId={props.sessionId!} />
          </Show>
          <Composer
            disabled={props.disabled}
            pending={props.pending}
            running={props.running}
            stopping={props.stopping}
            onStop={props.onStop}
            onSubmit={props.onSubmit}
            models={props.models}
            mode={props.mode}
            modelId={props.modelId}
            effort={props.effort}
            defaultModelId={props.defaultModelId}
            defaultEffort={props.defaultEffort}
            onModeChange={props.onModeChange}
            onModelChange={props.onModelChange}
            onEffortChange={props.onEffortChange}
            messages={props.messages}
            draftKey={props.draftKey}
            pendingText={props.pendingText}
            workspaceId={props.workspaceId}
            onCompact={props.onCompact}
            compacting={props.compacting}
          />
        </div>
      </div>
    </div>
  )
}

// src/components/chat/ChatPanel.tsx
import { useEffect, useRef } from 'react'

import type { ChatMessage } from '../../api/messages'
import type { CatalogModel } from '../../api/models'
import type { AgentMode } from '../../api/sessions'
import type { AgentPhase } from '../../state/chatStore'
import { Composer } from './Composer'
import { EditReviewStrip } from './EditReviewStrip'
import { Transcript } from './Transcript'
import type { AttachmentMeta, FileAttachment } from './textAttachments'
import type { PlanView } from './toolCallView'
import styles from './ChatPanel.module.css'

export type ChatPanelProps = {
  messages: ChatMessage[]
  sessionId: string | null
  echo: string | null
  /** Chips for the pending echo's attachments, before the stored row exists. */
  echoFiles: AttachmentMeta[]
  phase: AgentPhase
  mode: AgentMode
  deciding: boolean
  buildDisabled: boolean
  onDecide: (callId: string, decision: 'approve' | 'reject') => void
  onBuild: (path: string) => void
  onViewPlan: (plan: PlanView) => void
  disabled: boolean
  pending: boolean
  running: boolean
  stopping: boolean
  onStop: () => void
  onSubmit: (text: string, images?: File[], files?: FileAttachment[]) => Promise<boolean>
  models: CatalogModel[]
  modelId: string | null
  effort: string | null
  defaultModelId: string
  defaultEffort: string | null
  onModeChange: (mode: AgentMode) => void
  onModelChange: (model: string | null) => void
  onEffortChange: (effort: string | null) => void
  draftKey: string
  pendingText?: string | null
  workspaceId?: string | null
  onCompact?: () => void
  compacting?: boolean
  /** Show the pending edit review strip above the composer. */
  showReviewStrip?: boolean
}

export function ChatPanel({
  messages,
  sessionId,
  echo,
  echoFiles,
  phase,
  mode,
  deciding,
  buildDisabled,
  onDecide,
  onBuild,
  onViewPlan,
  disabled,
  pending,
  running,
  stopping,
  onStop,
  onSubmit,
  models,
  modelId,
  effort,
  defaultModelId,
  defaultEffort,
  onModeChange,
  onModelChange,
  onEffortChange,
  draftKey,
  pendingText = null,
  workspaceId = null,
  onCompact,
  compacting = false,
  showReviewStrip = false
}: ChatPanelProps) {
  const threadRef = useRef<HTMLDivElement>(null)
  const dockRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const dock = dockRef.current
    const thread = threadRef.current
    if (!dock || !thread) {
      return
    }
    const apply = () => {
      thread.style.setProperty('--dock-height', `${dock.offsetHeight}px`)
      const composer = dock.lastElementChild
      if (composer instanceof HTMLElement) {
        thread.style.setProperty('--composer-height', `${composer.offsetHeight}px`)
      }
    }
    apply()
    const observer = new ResizeObserver(apply)
    observer.observe(dock)
    return () => observer.disconnect()
  }, [sessionId, draftKey, showReviewStrip])

  return (
    <div className={styles.chat}>
      <div className={styles.thread} ref={threadRef}>
        <Transcript
          messages={messages}
          sessionId={sessionId}
          echo={echo}
          echoFiles={echoFiles}
          phase={phase}
          mode={mode}
          deciding={deciding}
          buildDisabled={buildDisabled}
          onDecide={onDecide}
          onBuild={onBuild}
          onViewPlan={onViewPlan}
        />
        <div className={styles.dock} ref={dockRef}>
          {showReviewStrip && sessionId ? (
            <EditReviewStrip key={sessionId} sessionId={sessionId} />
          ) : null}
          <Composer
            disabled={disabled}
            pending={pending}
            running={running}
            stopping={stopping}
            onStop={onStop}
            onSubmit={onSubmit}
            models={models}
            mode={mode}
            modelId={modelId}
            effort={effort}
            defaultModelId={defaultModelId}
            defaultEffort={defaultEffort}
            onModeChange={onModeChange}
            onModelChange={onModelChange}
            onEffortChange={onEffortChange}
            messages={messages}
            draftKey={draftKey}
            pendingText={pendingText}
            workspaceId={workspaceId}
            onCompact={onCompact}
            compacting={compacting}
          />
        </div>
      </div>
    </div>
  )
}
