// src/solid/components/chat/ChatHeader.tsx
/** @jsxImportSource solid-js */
import { Show } from 'solid-js'

import { ApiStatus } from '../layout/ApiStatus'
import { IndexStatusLine } from '../layout/IndexStatusLine'
import { McpTray } from '../layout/McpTray'
import styles from '../../../components/chat/ChatHeader.module.css'

export function ChatHeader(props: { sessionTitle: string }) {
  return (
    <header class={styles.header} data-tauri-drag-region="deep">
      <div class={styles.leading}>
        <IndexStatusLine />
      </div>
      <Show when={props.sessionTitle}>
        <span class={styles.title}>{props.sessionTitle}</span>
      </Show>
      <div class={styles.actions}>
        <McpTray />
        <ApiStatus />
      </div>
    </header>
  )
}

// src/components/chat/ChatHeader.tsx
import { ApiStatus } from '../layout/ApiStatus'
import { IndexStatusLine } from '../layout/IndexStatusLine'
import { McpTray } from '../layout/McpTray'
import styles from './ChatHeader.module.css'

type ChatHeaderProps = {
  sessionTitle: string
}

export function ChatHeader({ sessionTitle }: ChatHeaderProps) {
  return (
    <header className={styles.header} data-tauri-drag-region="deep">
      <div className={styles.leading}>
        <IndexStatusLine />
      </div>
      {sessionTitle ? <span className={styles.title}>{sessionTitle}</span> : null}
      <div className={styles.actions}>
        <McpTray />
        <ApiStatus />
      </div>
    </header>
  )
}
