// src/solid/components/chat/FileEditSummary.tsx
/** @jsxImportSource solid-js */
import { For, Show } from 'solid-js'

import type { MockFileEdit } from '../../../mock/chat'
import styles from '../../../components/chat/FileEditSummary.module.css'

export function FileEditSummary(props: {
  filesEdited: number
  additions: number
  deletions: number
  files: MockFileEdit[]
}) {
  return (
    <div class={styles.widget}>
      <div class={styles.header}>
        <div class={styles.summary}>
          <span>
            {props.filesEdited} file{props.filesEdited === 1 ? '' : 's'} edited
          </span>
          <span class={styles.counts}>
            <span class={styles.add}>+{props.additions}</span>
            <span class={styles.del}>-{props.deletions}</span>
          </span>
        </div>
        <button type="button" class={styles.review} disabled title="Review window arrives in M6">
          Review ↗
        </button>
      </div>
      <ul class={styles.list}>
        <For each={props.files}>
          {(file) => (
            <li>
              <button type="button" class={styles.row}>
                <span class={styles.path}>{file.path}</span>
                <span class={styles.rowCounts}>
                  <span class={styles.add}>+{file.additions}</span>
                  <span class={styles.del}>-{file.deletions}</span>
                </span>
                <Show when={file.unread}>
                  <span class={styles.dot} aria-label="Unread" />
                </Show>
                <span class={styles.chevron} aria-hidden="true">
                  ▾
                </span>
              </button>
            </li>
          )}
        </For>
      </ul>
    </div>
  )
}

// src/components/chat/FileEditSummary.tsx
import type { MockFileEdit } from '../../mock/chat'
import styles from './FileEditSummary.module.css'

type FileEditSummaryProps = {
  filesEdited: number
  additions: number
  deletions: number
  files: MockFileEdit[]
}

export function FileEditSummary({
  filesEdited,
  additions,
  deletions,
  files
}: FileEditSummaryProps) {
  return (
    <div className={styles.widget}>
      <div className={styles.header}>
        <div className={styles.summary}>
          <span>
            {filesEdited} file{filesEdited === 1 ? '' : 's'} edited
          </span>
          <span className={styles.counts}>
            <span className={styles.add}>+{additions}</span>
            <span className={styles.del}>-{deletions}</span>
          </span>
        </div>
        {/* Review destination arrives with M6 — keep affordance visible but inert. */}
        <button
          type="button"
          className={styles.review}
          disabled
          title="Review window arrives in M6"
        >
          Review ↗
        </button>
      </div>

      <ul className={styles.list}>
        {files.map((file) => (
          <li key={file.path}>
            <button type="button" className={styles.row}>
              <span className={styles.path}>{file.path}</span>
              <span className={styles.rowCounts}>
                <span className={styles.add}>+{file.additions}</span>
                <span className={styles.del}>-{file.deletions}</span>
              </span>
              {file.unread ? <span className={styles.dot} aria-label="Unread" /> : null}
              <span className={styles.chevron} aria-hidden>
                ▾
              </span>
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}
