// src/solid/components/chat/MermaidDiagram.tsx
/** @jsxImportSource solid-js */
import { createEffect, createSignal, onCleanup, Show } from 'solid-js'

import { renderMermaid } from '../../../components/chat/mermaid'
import styles from '../../../components/chat/AssistantMarkdown.module.css'

export function MermaidDiagram(props: { source: string; lines?: string }) {
  const [result, setResult] = createSignal<{ source: string; svg: string } | null>(null)

  createEffect(() => {
    const source = props.source
    let active = true
    void renderMermaid(source).then(
      (svg) => {
        if (active) {
          setResult({ source, svg })
        }
      },
      () => {
        // No result: the source fence is the fallback.
      }
    )
    onCleanup(() => {
      active = false
    })
  })

  const svg = () => (result()?.source === props.source ? result()!.svg : null)

  return (
    <Show
      when={svg()}
      fallback={
        <pre class={styles.diagramSource} data-md-lines={props.lines}>
          <code>{props.source}</code>
        </pre>
      }
    >
      {(markup) => (
        <div class={styles.diagram} data-md-lines={props.lines}>
          <div class={styles.diagramSvg} role="img" aria-label="Diagram" innerHTML={markup()} />
          <span class={styles.srOnly} data-find-ignore>
            {props.source}
          </span>
        </div>
      )}
    </Show>
  )
}

// src/components/chat/MermaidDiagram.tsx
import { memo, useEffect, useState } from 'react'

import { renderMermaid } from './mermaid'
import styles from './AssistantMarkdown.module.css'

/**
 * One fenced `mermaid` block. The source fence stays on screen until the SVG is
 * ready, and stays on screen for good when mermaid cannot parse it.
 */
export const MermaidDiagram = memo(function MermaidDiagram({ source }: { source: string }) {
  // The SVG is paired with the source it came from, so a source change falls
  // back to the fence immediately without a reset render.
  const [result, setResult] = useState<{ source: string; svg: string } | null>(null)

  useEffect(() => {
    let active = true
    renderMermaid(source).then(
      (svg) => {
        if (active) {
          setResult({ source, svg })
        }
      },
      () => {
        // No result: the source fence is the fallback.
      }
    )
    return () => {
      active = false
    }
  }, [source])

  const svg = result?.source === source ? result.svg : null

  if (svg === null) {
    return (
      <pre className={styles.diagramSource}>
        <code>{source}</code>
      </pre>
    )
  }

  return (
    <div className={styles.diagram}>
      <div
        className={styles.diagramSvg}
        role="img"
        aria-label="Diagram"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <span className={styles.srOnly} data-find-ignore>
        {source}
      </span>
    </div>
  )
})
