// src/solid/pages/workspaces/WorkspacesPage.tsx
/** @jsxImportSource solid-js */
import { useNavigate } from '@solidjs/router'
import { Folder, MagnifyingGlass } from '../../ui/icons'
import { createEffect, createMemo, createSignal, For, Show } from 'solid-js'

import { pickWorkspaceRoot } from '../../../infra/pickWorkspaceRoot'
import styles from '../../../pages/workspaces/WorkspacesPage.module.css'
import { patchWorkspaces, workspaces } from '../../state/host'

export function WorkspacesPage() {
  const navigate = useNavigate()
  const [query, setQuery] = createSignal('')
  const [creating, setCreating] = createSignal(false)

  createEffect(() => {
    if (!workspaces.loaded) {
      void workspaces.loadWorkspaces()
    }
  })

  const visible = createMemo(() => {
    const needle = query().trim().toLowerCase()
    const list = workspaces.workspaces
    return needle
      ? list.filter(
          (workspace) =>
            workspace.name.toLowerCase().includes(needle) ||
            workspace.root.toLowerCase().includes(needle)
        )
      : list
  })

  async function handleNew() {
    setCreating(true)
    try {
      const root = await pickWorkspaceRoot()
      if (root == null) {
        return
      }
      await workspaces.addWorkspace(root)
      if (workspaces.error) {
        return
      }
      navigate('/')
    } catch (err) {
      patchWorkspaces({
        error: err instanceof Error ? err.message : 'Failed to open the folder dialog'
      })
    } finally {
      setCreating(false)
    }
  }

  function openWorkspace(id: string) {
    workspaces.selectWorkspace(id)
    navigate('/')
  }

  function handleRemove(id: string, name: string) {
    if (!window.confirm(`Remove “${name}”? Its sessions will be deleted.`)) {
      return
    }
    void workspaces.removeWorkspace(id)
  }

  const empty = () => workspaces.loaded && workspaces.workspaces.length === 0

  return (
    <div class={styles.page}>
      <div class={styles.column}>
        <header class={styles.top}>
          <div class={styles.heading}>
            <Show when={workspaces.activeWorkspaceId}>
              <button type="button" class={styles.back} onClick={() => navigate('/')}>
                ← Chat
              </button>
            </Show>
            <h1 class={styles.title}>Workspaces</h1>
          </div>
          <div class={styles.tools}>
            <label class={styles.search}>
              <MagnifyingGlass size={14} aria-hidden />
              <input
                value={query()}
                onInput={(event) => setQuery(event.currentTarget.value)}
                placeholder="Search"
                aria-label="Search workspaces"
              />
            </label>
            <button
              type="button"
              class={styles.primary}
              onClick={() => void handleNew()}
              disabled={creating()}
            >
              New workspace
            </button>
          </div>
        </header>

        <Show when={workspaces.error}>
          <div class={styles.banner} role="alert">
            {workspaces.error}
          </div>
        </Show>

        <Show when={workspaces.loaded} fallback={<p class={styles.status}>Loading…</p>}>
          <Show
            when={!empty()}
            fallback={
              <div class={styles.empty}>
                <Folder class={styles.mark} size={72} aria-hidden />
                <h2 class={styles.emptyTitle}>Looking to start a workspace?</h2>
                <p class={styles.emptyCopy}>
                  Open a directory. Sessions stay with that folder, and the agent works from its
                  root.
                </p>
                <button
                  type="button"
                  class={styles.emptyAction}
                  onClick={() => void handleNew()}
                  disabled={creating()}
                >
                  New workspace
                </button>
              </div>
            }
          >
            <ul class={styles.list}>
              <Show
                when={visible().length > 0}
                fallback={<li class={styles.noMatch}>No workspaces match “{query().trim()}”.</li>}
              >
                <For each={visible()}>
                  {(workspace) => {
                    const current = () => workspace.id === workspaces.activeWorkspaceId
                    return (
                      <li>
                        <article class={styles.card}>
                          <div class={styles.cardHead}>
                            <button
                              type="button"
                              class={styles.cardName}
                              onClick={() => openWorkspace(workspace.id)}
                            >
                              {workspace.name}
                              <Show when={current()}>
                                <span class={styles.current}>Current</span>
                              </Show>
                            </button>
                            <div class={styles.actions}>
                              <button
                                type="button"
                                class={styles.open}
                                onClick={() => openWorkspace(workspace.id)}
                              >
                                Open
                              </button>
                              <button
                                type="button"
                                class={styles.remove}
                                aria-label={`Remove ${workspace.name}`}
                                onClick={() => handleRemove(workspace.id, workspace.name)}
                              >
                                Remove
                              </button>
                            </div>
                          </div>
                          <div class={styles.cardRoot} title={workspace.root}>
                            {workspace.root}
                          </div>
                        </article>
                      </li>
                    )
                  }}
                </For>
              </Show>
            </ul>
          </Show>
        </Show>
      </div>
    </div>
  )
}

// src/pages/workspaces/WorkspacesPage.tsx
import { Folders, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { pickWorkspaceRoot } from '../../infra/pickWorkspaceRoot'
import { useWorkspaceStore } from '../../state/workspaceStore'
import styles from './WorkspacesPage.module.css'

export function WorkspacesPage() {
  const navigate = useNavigate()
  const workspaces = useWorkspaceStore((state) => state.workspaces)
  const activeWorkspaceId = useWorkspaceStore((state) => state.activeWorkspaceId)
  const loaded = useWorkspaceStore((state) => state.loaded)
  const error = useWorkspaceStore((state) => state.error)
  const loadWorkspaces = useWorkspaceStore((state) => state.loadWorkspaces)
  const selectWorkspace = useWorkspaceStore((state) => state.selectWorkspace)
  const addWorkspace = useWorkspaceStore((state) => state.addWorkspace)
  const removeWorkspace = useWorkspaceStore((state) => state.removeWorkspace)
  const [query, setQuery] = useState('')
  const [creating, setCreating] = useState(false)

  useEffect(() => {
    if (!loaded) {
      void loadWorkspaces()
    }
  }, [loaded, loadWorkspaces])

  const visible = useMemo(() => {
    const needle = query.trim().toLowerCase()
    const matched = needle
      ? workspaces.filter(
          (workspace) =>
            workspace.name.toLowerCase().includes(needle) ||
            workspace.root.toLowerCase().includes(needle)
        )
      : workspaces
    return matched
  }, [workspaces, query])

  async function handleNew() {
    setCreating(true)
    try {
      const root = await pickWorkspaceRoot()
      if (root == null) {
        return
      }
      await addWorkspace(root)
      if (useWorkspaceStore.getState().error) {
        return
      }
      navigate('/')
    } catch (err) {
      useWorkspaceStore.setState({
        error: err instanceof Error ? err.message : 'Failed to open the folder dialog'
      })
    } finally {
      setCreating(false)
    }
  }

  function openWorkspace(id: string) {
    selectWorkspace(id)
    navigate('/')
  }

  function handleRemove(id: string, name: string) {
    if (!window.confirm(`Remove “${name}”? Its sessions will be deleted.`)) {
      return
    }
    void removeWorkspace(id)
  }

  const empty = loaded && workspaces.length === 0

  return (
    <div className={styles.page}>
      <div className={styles.column}>
        <header className={styles.top}>
          <div className={styles.heading}>
            {activeWorkspaceId ? (
              <button type="button" className={styles.back} onClick={() => navigate('/')}>
                ← Chat
              </button>
            ) : null}
            <h1 className={styles.title}>Workspaces</h1>
          </div>
          <div className={styles.tools}>
            <label className={styles.search}>
              <SearchIcon />
              <input
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Search"
                aria-label="Search workspaces"
              />
            </label>
            <button
              type="button"
              className={styles.primary}
              onClick={() => void handleNew()}
              disabled={creating}
            >
              New workspace
            </button>
          </div>
        </header>

        {error ? (
          <div className={styles.banner} role="alert">
            {error}
          </div>
        ) : null}

        {!loaded ? (
          <p className={styles.status}>Loading…</p>
        ) : empty ? (
          <div className={styles.empty}>
            <FolderMark />
            <h2 className={styles.emptyTitle}>Looking to start a workspace?</h2>
            <p className={styles.emptyCopy}>
              Open a directory. Sessions stay with that folder, and the agent works from its root.
            </p>
            <button
              type="button"
              className={styles.emptyAction}
              onClick={() => void handleNew()}
              disabled={creating}
            >
              New workspace
            </button>
          </div>
        ) : (
          <ul className={styles.list}>
            {visible.length === 0 ? (
              <li className={styles.noMatch}>No workspaces match “{query.trim()}”.</li>
            ) : (
              visible.map((workspace) => {
                const current = workspace.id === activeWorkspaceId
                return (
                  <li key={workspace.id}>
                    <article className={styles.card}>
                      <div className={styles.cardHead}>
                        <button
                          type="button"
                          className={styles.cardName}
                          onClick={() => openWorkspace(workspace.id)}
                        >
                          {workspace.name}
                          {current ? <span className={styles.current}>Current</span> : null}
                        </button>
                        <div className={styles.actions}>
                          <button
                            type="button"
                            className={styles.open}
                            onClick={() => openWorkspace(workspace.id)}
                          >
                            Open
                          </button>
                          <button
                            type="button"
                            className={styles.remove}
                            aria-label={`Remove ${workspace.name}`}
                            onClick={() => handleRemove(workspace.id, workspace.name)}
                          >
                            Remove
                          </button>
                        </div>
                      </div>
                      <div className={styles.cardRoot} title={workspace.root}>
                        {workspace.root}
                      </div>
                    </article>
                  </li>
                )
              })
            )}
          </ul>
        )}
      </div>
    </div>
  )
}

function SearchIcon() {
  return <Search size={14} strokeWidth={1.75} aria-hidden />
}

function FolderMark() {
  return <Folders className={styles.mark} size={72} strokeWidth={1.5} aria-hidden />
}
