// src/components/review/FileViewDialog.tsx
import { useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'

import type { ReviewFile, ReviewLine } from '../../api/review'
import { AssistantMarkdown } from '../chat/AssistantMarkdown'
import { expandReviewLines, type ReviewView } from './diffView'
import { DiffRows } from './DiffRows'
import diffStyles from './DiffList.module.css'
import type { PaintedToken } from './highlight'
import styles from './FileViewDialog.module.css'

type FileMode = ReviewView | 'preview'

const VIEWS: { id: FileMode; label: string }[] = [
  { id: 'diff', label: 'Diff' },
  { id: 'current', label: 'Current' },
  { id: 'previous', label: 'Previous' },
  { id: 'preview', label: 'Preview' }
]

function isMarkdown(path: string): boolean {
  const name = path.split('/').pop() ?? path
  const dot = name.lastIndexOf('.')
  if (dot < 0) {
    return false
  }
  const ext = name.slice(dot + 1).toLowerCase()
  return ext === 'md' || ext === 'markdown'
}

type FileViewDialogProps = {
  file: ReviewFile | null
  baseline: PaintedToken[][]
  current: PaintedToken[][]
  onClose: () => void
}

export function FileViewDialog({ file, baseline, current, onClose }: FileViewDialogProps) {
  return (
    <Dialog.Root
      open={file !== null}
      onOpenChange={(next) => {
        if (!next) {
          onClose()
        }
      }}
    >
      <Dialog.Portal>
        <Dialog.Overlay className={styles.overlay} />
        <Dialog.Content className={styles.panel}>
          {file ? (
            <FileView key={file.path} file={file} baseline={baseline} current={current} />
          ) : null}
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}

function FileView({
  file,
  baseline,
  current
}: {
  file: ReviewFile
  baseline: PaintedToken[][]
  current: PaintedToken[][]
}) {
  const [view, setView] = useState<FileMode>('diff')
  const markdown = isMarkdown(file.path)
  const modes = markdown ? VIEWS : VIEWS.filter((item) => item.id !== 'preview')
  const sides = { baseline, current }
  const diffLines = expandReviewLines(file.lines, file.baseline, file.current)
  const previewText = file.status === 'deleted' ? file.baseline : file.current
  const note =
    view === 'previous' && file.status === 'added'
      ? 'File added'
      : view === 'current' && file.status === 'deleted'
        ? 'File deleted'
        : null
  const whole = view === 'previous' ? baseline : view === 'current' ? current : null

  return (
    <>
      <header className={styles.head}>
        <Dialog.Title className={styles.title}>{file.path}</Dialog.Title>
        <div className={styles.views} role="radiogroup" aria-label="File version">
          {modes.map((item) => (
            <button
              key={item.id}
              type="button"
              role="radio"
              aria-checked={view === item.id}
              className={view === item.id ? styles.viewActive : styles.view}
              onClick={() => setView(item.id)}
            >
              {item.label}
            </button>
          ))}
        </div>
        <Dialog.Close className={styles.close}>Close</Dialog.Close>
      </header>
      <Dialog.Description className={styles.srOnly}>
        {note ??
          (view === 'preview'
            ? `Preview of ${file.path}`
            : view === 'diff'
              ? `Diff of ${file.path}`
              : view === 'previous'
                ? `Previous contents of ${file.path}`
                : `Current contents of ${file.path}`)}
      </Dialog.Description>
      <div className={view === 'preview' ? styles.bodyPreview : styles.body}>
        {note ? (
          <p className={styles.empty}>{note}</p>
        ) : view === 'preview' ? (
          previewText === '' ? (
            <p className={styles.empty}>This file is empty.</p>
          ) : (
            <AssistantMarkdown text={previewText} document />
          )
        ) : view === 'diff' ? (
          <div className={diffStyles.wide}>
            <DiffRows lines={diffLines} tokensForLine={(line) => tokensFor(line, sides)} />
          </div>
        ) : whole && whole.length === 0 ? (
          <p className={styles.empty}>This file is empty.</p>
        ) : (
          <div className={styles.sheet}>
            <div className={styles.gutter} aria-hidden="true">
              {whole?.map((_, index) => (
                <div key={index} className={styles.num}>
                  {index + 1}
                </div>
              ))}
            </div>
            <div className={styles.codeCol}>
              {whole?.map((tokens, index) => (
                <div key={index} className={styles.code}>
                  {tokens.every((token) => token.text === '')
                    ? '\u00a0'
                    : tokens.map((token, tokenIndex) => (
                        <span
                          key={tokenIndex}
                          style={token.color ? { color: token.color } : undefined}
                        >
                          {token.text}
                        </span>
                      ))}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </>
  )
}

function tokensFor(
  line: ReviewLine,
  sides: { baseline: PaintedToken[][]; current: PaintedToken[][] }
): PaintedToken[] {
  if (line.kind === 'gap') {
    return [{ text: line.text }]
  }
  const source = line.kind === 'delete' ? sides.baseline : sides.current
  const number = line.kind === 'delete' ? line.old_line : line.new_line
  if (number == null) {
    return [{ text: line.text }]
  }
  return source[number - 1] ?? [{ text: line.text }]
}

// src/features/review/FileViewDialog.tsx
/** @jsxImportSource solid-js */
import { Dialog } from '@kobalte/core/dialog'
import { createSignal, For, Show } from 'solid-js'

import type { ReviewFile, ReviewLine } from '../../api/review'
import { expandReviewLines, type ReviewView } from './diffView'
import type { PaintedToken } from './highlight'
import diffStyles from './DiffList.module.css'
import styles from './FileViewDialog.module.css'
import { AssistantMarkdown } from '../chat/AssistantMarkdown'
import { DiffRows } from './DiffRows'

type FileMode = ReviewView | 'preview'

const VIEWS: { id: FileMode; label: string }[] = [
  { id: 'diff', label: 'Diff' },
  { id: 'current', label: 'Current' },
  { id: 'previous', label: 'Previous' },
  { id: 'preview', label: 'Preview' }
]

function isMarkdown(path: string): boolean {
  const name = path.split('/').pop() ?? path
  const dot = name.lastIndexOf('.')
  if (dot < 0) {
    return false
  }
  const ext = name.slice(dot + 1).toLowerCase()
  return ext === 'md' || ext === 'markdown'
}

export function FileViewDialog(props: {
  file: ReviewFile | null
  baseline: PaintedToken[][]
  current: PaintedToken[][]
  onClose: () => void
}) {
  return (
    <Dialog
      open={props.file !== null}
      onOpenChange={(next) => {
        if (!next) {
          props.onClose()
        }
      }}
    >
      <Dialog.Portal>
        <Dialog.Overlay class={styles.overlay} />
        <Dialog.Content class={styles.panel}>
          <Show when={props.file} keyed>
            {(file) => <FileView file={file} baseline={props.baseline} current={props.current} />}
          </Show>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog>
  )
}

function FileView(props: {
  file: ReviewFile
  baseline: PaintedToken[][]
  current: PaintedToken[][]
}) {
  const [view, setView] = createSignal<FileMode>('diff')
  const markdown = () => isMarkdown(props.file.path)
  const modes = () => (markdown() ? VIEWS : VIEWS.filter((item) => item.id !== 'preview'))
  const sides = () => ({ baseline: props.baseline, current: props.current })
  const diffLines = () =>
    expandReviewLines(props.file.lines, props.file.baseline, props.file.current)
  const previewText = () =>
    props.file.status === 'deleted' ? props.file.baseline : props.file.current
  const note = () =>
    view() === 'previous' && props.file.status === 'added'
      ? 'File added'
      : view() === 'current' && props.file.status === 'deleted'
        ? 'File deleted'
        : null
  const whole = () =>
    view() === 'previous' ? props.baseline : view() === 'current' ? props.current : null
  const description = () =>
    note() ??
    (view() === 'preview'
      ? `Preview of ${props.file.path}`
      : view() === 'diff'
        ? `Diff of ${props.file.path}`
        : view() === 'previous'
          ? `Previous contents of ${props.file.path}`
          : `Current contents of ${props.file.path}`)

  return (
    <>
      <header class={styles.head}>
        <Dialog.Title class={styles.title}>{props.file.path}</Dialog.Title>
        <div class={styles.views} role="radiogroup" aria-label="File version">
          <For each={modes()}>
            {(item) => (
              <button
                type="button"
                role="radio"
                aria-checked={view() === item.id}
                class={view() === item.id ? styles.viewActive : styles.view}
                onClick={() => setView(item.id)}
              >
                {item.label}
              </button>
            )}
          </For>
        </div>
        <Dialog.CloseButton class={styles.close}>Close</Dialog.CloseButton>
      </header>
      <Dialog.Description class={styles.srOnly}>{description()}</Dialog.Description>
      <div class={view() === 'preview' ? styles.bodyPreview : styles.body}>
        <Show when={!note()} fallback={<p class={styles.empty}>{note()}</p>}>
          <Show
            when={view() !== 'preview'}
            fallback={
              <Show
                when={previewText() !== ''}
                fallback={<p class={styles.empty}>This file is empty.</p>}
              >
                <AssistantMarkdown text={previewText()} document />
              </Show>
            }
          >
            <Show
              when={view() === 'diff'}
              fallback={
                <Show
                  when={(whole()?.length ?? 0) > 0}
                  fallback={<p class={styles.empty}>This file is empty.</p>}
                >
                  <div class={styles.sheet}>
                    <div class={styles.gutter} aria-hidden="true">
                      <For each={whole() ?? []}>
                        {(_, index) => <div class={styles.num}>{index() + 1}</div>}
                      </For>
                    </div>
                    <div class={styles.codeCol}>
                      <For each={whole() ?? []}>
                        {(tokens) => (
                          <div class={styles.code}>
                            {tokens.every((token) => token.text === '')
                              ? '\u00a0'
                              : tokens.map((token) => (
                                  <span style={token.color ? { color: token.color } : undefined}>
                                    {token.text}
                                  </span>
                                ))}
                          </div>
                        )}
                      </For>
                    </div>
                  </div>
                </Show>
              }
            >
              <div class={diffStyles.wide}>
                <DiffRows lines={diffLines()} tokensForLine={(line) => tokensFor(line, sides())} />
              </div>
            </Show>
          </Show>
        </Show>
      </div>
    </>
  )
}

function tokensFor(
  line: ReviewLine,
  sides: { baseline: PaintedToken[][]; current: PaintedToken[][] }
): PaintedToken[] {
  if (line.kind === 'gap') {
    return [{ text: line.text }]
  }
  const source = line.kind === 'delete' ? sides.baseline : sides.current
  const number = line.kind === 'delete' ? line.old_line : line.new_line
  if (number == null) {
    return [{ text: line.text }]
  }
  return source[number - 1] ?? [{ text: line.text }]
}
