// src/components/docs/DocTree.tsx
import type { TreeNode } from '../review/tree'
import styles from './DocTree.module.css'

type DocTreeProps = {
  nodes: TreeNode[]
  selected: string | null
  /** Directory paths the user has folded closed. */
  collapsed: ReadonlySet<string>
  onSelect: (path: string) => void
  onToggle: (path: string) => void
}

export function DocTree({ nodes, selected, collapsed, onSelect, onToggle }: DocTreeProps) {
  return (
    <nav className={styles.tree} aria-label="Documentation">
      <TreeLevel
        nodes={nodes}
        depth={0}
        selected={selected}
        collapsed={collapsed}
        onSelect={onSelect}
        onToggle={onToggle}
      />
    </nav>
  )
}

function TreeLevel({
  nodes,
  depth,
  selected,
  collapsed,
  onSelect,
  onToggle
}: DocTreeProps & { depth: number }) {
  return (
    <ul className={styles.list}>
      {nodes.map((node) => {
        const indent = { paddingLeft: 12 + depth * 14 }
        if (node.kind === 'dir') {
          const open = !collapsed.has(node.path)
          return (
            <li key={`${node.kind}:${node.path}`}>
              <button
                type="button"
                className={styles.dir}
                style={indent}
                aria-expanded={open}
                onClick={() => onToggle(node.path)}
              >
                <span className={styles.caret} aria-hidden>
                  {open ? '▾' : '▸'}
                </span>
                {node.name}
              </button>
              {open ? (
                <TreeLevel
                  nodes={node.children}
                  depth={depth + 1}
                  selected={selected}
                  collapsed={collapsed}
                  onSelect={onSelect}
                  onToggle={onToggle}
                />
              ) : null}
            </li>
          )
        }
        return (
          <li key={`${node.kind}:${node.path}`}>
            <button
              type="button"
              className={node.path === selected ? styles.fileActive : styles.file}
              style={indent}
              aria-current={node.path === selected ? 'true' : undefined}
              onClick={() => onSelect(node.path)}
            >
              {node.name}
            </button>
          </li>
        )
      })}
    </ul>
  )
}

// src/features/docs/DocTree.tsx
/** @jsxImportSource solid-js */
import { For, Show } from 'solid-js'

import type { TreeNode } from '../review/tree'
import styles from './DocTree.module.css'

export function DocTree(props: {
  nodes: TreeNode[]
  selected: string | null
  collapsed: ReadonlySet<string>
  onSelect: (path: string) => void
  onToggle: (path: string) => void
}) {
  return (
    <nav class={styles.tree} aria-label="Documentation">
      <TreeLevel
        nodes={props.nodes}
        depth={0}
        selected={props.selected}
        collapsed={props.collapsed}
        onSelect={props.onSelect}
        onToggle={props.onToggle}
      />
    </nav>
  )
}

function TreeLevel(props: {
  nodes: TreeNode[]
  depth: number
  selected: string | null
  collapsed: ReadonlySet<string>
  onSelect: (path: string) => void
  onToggle: (path: string) => void
}) {
  return (
    <ul class={styles.list}>
      <For each={props.nodes}>
        {(node) => {
          const indent = { 'padding-left': `${12 + props.depth * 14}px` }
          return (
            <Show
              when={node.kind === 'dir'}
              fallback={
                <li>
                  <button
                    type="button"
                    class={node.path === props.selected ? styles.fileActive : styles.file}
                    style={indent}
                    aria-current={node.path === props.selected ? 'true' : undefined}
                    onClick={() => props.onSelect(node.path)}
                  >
                    {node.name}
                  </button>
                </li>
              }
            >
              <li>
                <button
                  type="button"
                  class={styles.dir}
                  style={indent}
                  aria-expanded={!props.collapsed.has(node.path)}
                  onClick={() => props.onToggle(node.path)}
                >
                  <span class={styles.caret} aria-hidden="true">
                    {props.collapsed.has(node.path) ? '▸' : '▾'}
                  </span>
                  {node.name}
                </button>
                <Show when={!props.collapsed.has(node.path) && node.kind === 'dir'}>
                  <TreeLevel
                    nodes={node.kind === 'dir' ? node.children : []}
                    depth={props.depth + 1}
                    selected={props.selected}
                    collapsed={props.collapsed}
                    onSelect={props.onSelect}
                    onToggle={props.onToggle}
                  />
                </Show>
              </li>
            </Show>
          )
        }}
      </For>
    </ul>
  )
}
